name: connectsphere

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  mailpit:
    image: axllent/mailpit:v1.31.1
    container_name: mailpit
    ports:
      - 1025:1025
      - 8025:8025
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8025/api/v1/info"]
      interval: 5s
      timeout: 5s
      retries: 10

  connectsphere:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connectsphere
    ports:
      - 3000:3000
    env_file:
      - .env.example
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
