/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventRequestsRouteImport } from './routes/_authenticated/event-requests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSmokeRouteImport } from './routes/api/smoke'
import { Route as ApiUploadUrlRouteImport } from './routes/api/upload-url'
import { Route as AuthenticatedVenuesIndexRouteImport } from './routes/_authenticated/venues/index'
import { Route as AuthenticatedVenuesVenueIdRouteImport } from './routes/_authenticated/venues/$venueId'
import { Route as AuthenticatedVenuesNewRouteImport } from './routes/_authenticated/venues/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventRequestsRoute =
  AuthenticatedEventRequestsRouteImport.update({
    id: '/event-requests',
    path: '/event-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmokeRoute = ApiSmokeRouteImport.update({
  id: '/api/smoke',
  path: '/api/smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadUrlRoute = ApiUploadUrlRouteImport.update({
  id: '/api/upload-url',
  path: '/api/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVenuesIndexRoute =
  AuthenticatedVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesVenueIdRoute =
  AuthenticatedVenuesVenueIdRouteImport.update({
    id: '/venues/$venueId',
    path: '/venues/$venueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesNewRoute = AuthenticatedVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/event-requests': typeof AuthenticatedEventRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/venues/': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/event-requests': typeof AuthenticatedEventRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/venues': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/event-requests': typeof AuthenticatedEventRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/api/upload-url': typeof ApiUploadUrlRoute
  '/_authenticated/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/_authenticated/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/venues/': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/event-requests'
    | '/settings'
    | '/api/health'
    | '/api/smoke'
    | '/api/upload-url'
    | '/venues/$venueId'
    | '/venues/new'
    | '/api/auth/$'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/event-requests'
    | '/settings'
    | '/api/health'
    | '/api/smoke'
    | '/api/upload-url'
    | '/venues/$venueId'
    | '/venues/new'
    | '/api/auth/$'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/event-requests'
    | '/_authenticated/settings'
    | '/api/health'
    | '/api/smoke'
    | '/api/upload-url'
    | '/_authenticated/venues/$venueId'
    | '/_authenticated/venues/new'
    | '/api/auth/$'
    | '/_authenticated/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSmokeRoute: typeof ApiSmokeRoute
  ApiUploadUrlRoute: typeof ApiUploadUrlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event-requests': {
      id: '/_authenticated/event-requests'
      path: '/event-requests'
      fullPath: '/event-requests'
      preLoaderRoute: typeof AuthenticatedEventRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smoke': {
      id: '/api/smoke'
      path: '/api/smoke'
      fullPath: '/api/smoke'
      preLoaderRoute: typeof ApiSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-url': {
      id: '/api/upload-url'
      path: '/api/upload-url'
      fullPath: '/api/upload-url'
      preLoaderRoute: typeof ApiUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/venues/': {
      id: '/_authenticated/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof AuthenticatedVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/$venueId': {
      id: '/_authenticated/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof AuthenticatedVenuesVenueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/new': {
      id: '/_authenticated/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof AuthenticatedVenuesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventRequestsRoute: typeof AuthenticatedEventRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVenuesVenueIdRoute: typeof AuthenticatedVenuesVenueIdRoute
  AuthenticatedVenuesNewRoute: typeof AuthenticatedVenuesNewRoute
  AuthenticatedVenuesIndexRoute: typeof AuthenticatedVenuesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventRequestsRoute: AuthenticatedEventRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVenuesVenueIdRoute: AuthenticatedVenuesVenueIdRoute,
  AuthenticatedVenuesNewRoute: AuthenticatedVenuesNewRoute,
  AuthenticatedVenuesIndexRoute: AuthenticatedVenuesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSmokeRoute: ApiSmokeRoute,
  ApiUploadUrlRoute: ApiUploadUrlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
