/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSmokeRouteImport } from './routes/api/smoke'
import { Route as AuthenticatedCoordinationIndexRouteImport } from './routes/_authenticated/coordination/index'
import { Route as AuthenticatedEventRequestsIndexRouteImport } from './routes/_authenticated/event-requests/index'
import { Route as AuthenticatedEventRequestsNewRouteImport } from './routes/_authenticated/event-requests/new'
import { Route as AuthenticatedEventsEventIdRouteRouteImport } from './routes/_authenticated/events/$eventId/route'
import { Route as AuthenticatedVenueBookingsIndexRouteImport } from './routes/_authenticated/venue-bookings/index'
import { Route as AuthenticatedVenuesIndexRouteImport } from './routes/_authenticated/venues/index'
import { Route as AuthenticatedVenuesVenueIdRouteImport } from './routes/_authenticated/venues/$venueId'
import { Route as AuthenticatedVenuesAvailabilityRouteImport } from './routes/_authenticated/venues/availability'
import { Route as AuthenticatedVenuesNewRouteImport } from './routes/_authenticated/venues/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronNotificationsRouteImport } from './routes/api/cron/notifications'
import { Route as AuthenticatedEventRequestsReopenDraftIdRouteImport } from './routes/_authenticated/event-requests/reopenDraft.$id'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmokeRoute = ApiSmokeRouteImport.update({
  id: '/api/smoke',
  path: '/api/smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoordinationIndexRoute =
  AuthenticatedCoordinationIndexRouteImport.update({
    id: '/coordination/',
    path: '/coordination/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventRequestsIndexRoute =
  AuthenticatedEventRequestsIndexRouteImport.update({
    id: '/event-requests/',
    path: '/event-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventRequestsNewRoute =
  AuthenticatedEventRequestsNewRouteImport.update({
    id: '/event-requests/new',
    path: '/event-requests/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdRouteRoute =
  AuthenticatedEventsEventIdRouteRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenueBookingsIndexRoute =
  AuthenticatedVenueBookingsIndexRouteImport.update({
    id: '/venue-bookings/',
    path: '/venue-bookings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesIndexRoute =
  AuthenticatedVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesVenueIdRoute =
  AuthenticatedVenuesVenueIdRouteImport.update({
    id: '/venues/$venueId',
    path: '/venues/$venueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesAvailabilityRoute =
  AuthenticatedVenuesAvailabilityRouteImport.update({
    id: '/venues/availability',
    path: '/venues/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenuesNewRoute = AuthenticatedVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNotificationsRoute = ApiCronNotificationsRouteImport.update({
  id: '/api/cron/notifications',
  path: '/api/cron/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventRequestsReopenDraftIdRoute =
  AuthenticatedEventRequestsReopenDraftIdRouteImport.update({
    id: '/event-requests/reopenDraft/$id',
    path: '/event-requests/reopenDraft/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/event-requests/new': typeof AuthenticatedEventRequestsNewRoute
  '/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/venues/availability': typeof AuthenticatedVenuesAvailabilityRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/coordination/': typeof AuthenticatedCoordinationIndexRoute
  '/event-requests/': typeof AuthenticatedEventRequestsIndexRoute
  '/venue-bookings/': typeof AuthenticatedVenueBookingsIndexRoute
  '/venues/': typeof AuthenticatedVenuesIndexRoute
  '/event-requests/reopenDraft/$id': typeof AuthenticatedEventRequestsReopenDraftIdRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/event-requests/new': typeof AuthenticatedEventRequestsNewRoute
  '/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/venues/availability': typeof AuthenticatedVenuesAvailabilityRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/coordination': typeof AuthenticatedCoordinationIndexRoute
  '/event-requests': typeof AuthenticatedEventRequestsIndexRoute
  '/venue-bookings': typeof AuthenticatedVenueBookingsIndexRoute
  '/venues': typeof AuthenticatedVenuesIndexRoute
  '/event-requests/reopenDraft/$id': typeof AuthenticatedEventRequestsReopenDraftIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/smoke': typeof ApiSmokeRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/_authenticated/event-requests/new': typeof AuthenticatedEventRequestsNewRoute
  '/_authenticated/venues/$venueId': typeof AuthenticatedVenuesVenueIdRoute
  '/_authenticated/venues/availability': typeof AuthenticatedVenuesAvailabilityRoute
  '/_authenticated/venues/new': typeof AuthenticatedVenuesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notifications': typeof ApiCronNotificationsRoute
  '/_authenticated/coordination/': typeof AuthenticatedCoordinationIndexRoute
  '/_authenticated/event-requests/': typeof AuthenticatedEventRequestsIndexRoute
  '/_authenticated/venue-bookings/': typeof AuthenticatedVenueBookingsIndexRoute
  '/_authenticated/venues/': typeof AuthenticatedVenuesIndexRoute
  '/_authenticated/event-requests/reopenDraft/$id': typeof AuthenticatedEventRequestsReopenDraftIdRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/api/health'
    | '/api/smoke'
    | '/events/$eventId'
    | '/event-requests/new'
    | '/venues/$venueId'
    | '/venues/availability'
    | '/venues/new'
    | '/api/auth/$'
    | '/api/cron/notifications'
    | '/coordination/'
    | '/event-requests/'
    | '/venue-bookings/'
    | '/venues/'
    | '/event-requests/reopenDraft/$id'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/api/health'
    | '/api/smoke'
    | '/event-requests/new'
    | '/venues/$venueId'
    | '/venues/availability'
    | '/venues/new'
    | '/api/auth/$'
    | '/api/cron/notifications'
    | '/coordination'
    | '/event-requests'
    | '/venue-bookings'
    | '/venues'
    | '/event-requests/reopenDraft/$id'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/api/health'
    | '/api/smoke'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/event-requests/new'
    | '/_authenticated/venues/$venueId'
    | '/_authenticated/venues/availability'
    | '/_authenticated/venues/new'
    | '/api/auth/$'
    | '/api/cron/notifications'
    | '/_authenticated/coordination/'
    | '/_authenticated/event-requests/'
    | '/_authenticated/venue-bookings/'
    | '/_authenticated/venues/'
    | '/_authenticated/event-requests/reopenDraft/$id'
    | '/_authenticated/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSmokeRoute: typeof ApiSmokeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronNotificationsRoute: typeof ApiCronNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smoke': {
      id: '/api/smoke'
      path: '/api/smoke'
      fullPath: '/api/smoke'
      preLoaderRoute: typeof ApiSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coordination/': {
      id: '/_authenticated/coordination/'
      path: '/coordination'
      fullPath: '/coordination/'
      preLoaderRoute: typeof AuthenticatedCoordinationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event-requests/': {
      id: '/_authenticated/event-requests/'
      path: '/event-requests'
      fullPath: '/event-requests/'
      preLoaderRoute: typeof AuthenticatedEventRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event-requests/new': {
      id: '/_authenticated/event-requests/new'
      path: '/event-requests/new'
      fullPath: '/event-requests/new'
      preLoaderRoute: typeof AuthenticatedEventRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venue-bookings/': {
      id: '/_authenticated/venue-bookings/'
      path: '/venue-bookings'
      fullPath: '/venue-bookings/'
      preLoaderRoute: typeof AuthenticatedVenueBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/': {
      id: '/_authenticated/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof AuthenticatedVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/$venueId': {
      id: '/_authenticated/venues/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof AuthenticatedVenuesVenueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/availability': {
      id: '/_authenticated/venues/availability'
      path: '/venues/availability'
      fullPath: '/venues/availability'
      preLoaderRoute: typeof AuthenticatedVenuesAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/venues/new': {
      id: '/_authenticated/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof AuthenticatedVenuesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notifications': {
      id: '/api/cron/notifications'
      path: '/api/cron/notifications'
      fullPath: '/api/cron/notifications'
      preLoaderRoute: typeof ApiCronNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/event-requests/reopenDraft/$id': {
      id: '/_authenticated/event-requests/reopenDraft/$id'
      path: '/event-requests/reopenDraft/$id'
      fullPath: '/event-requests/reopenDraft/$id'
      preLoaderRoute: typeof AuthenticatedEventRequestsReopenDraftIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
  }
}

interface AuthenticatedEventsEventIdRouteRouteChildren {
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteRouteChildren: AuthenticatedEventsEventIdRouteRouteChildren =
  {
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteRouteWithChildren =
  AuthenticatedEventsEventIdRouteRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEventsEventIdRouteRoute: typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  AuthenticatedEventRequestsNewRoute: typeof AuthenticatedEventRequestsNewRoute
  AuthenticatedVenuesVenueIdRoute: typeof AuthenticatedVenuesVenueIdRoute
  AuthenticatedVenuesAvailabilityRoute: typeof AuthenticatedVenuesAvailabilityRoute
  AuthenticatedVenuesNewRoute: typeof AuthenticatedVenuesNewRoute
  AuthenticatedCoordinationIndexRoute: typeof AuthenticatedCoordinationIndexRoute
  AuthenticatedEventRequestsIndexRoute: typeof AuthenticatedEventRequestsIndexRoute
  AuthenticatedVenueBookingsIndexRoute: typeof AuthenticatedVenueBookingsIndexRoute
  AuthenticatedVenuesIndexRoute: typeof AuthenticatedVenuesIndexRoute
  AuthenticatedEventRequestsReopenDraftIdRoute: typeof AuthenticatedEventRequestsReopenDraftIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEventsEventIdRouteRoute:
    AuthenticatedEventsEventIdRouteRouteWithChildren,
  AuthenticatedEventRequestsNewRoute: AuthenticatedEventRequestsNewRoute,
  AuthenticatedVenuesVenueIdRoute: AuthenticatedVenuesVenueIdRoute,
  AuthenticatedVenuesAvailabilityRoute: AuthenticatedVenuesAvailabilityRoute,
  AuthenticatedVenuesNewRoute: AuthenticatedVenuesNewRoute,
  AuthenticatedCoordinationIndexRoute: AuthenticatedCoordinationIndexRoute,
  AuthenticatedEventRequestsIndexRoute: AuthenticatedEventRequestsIndexRoute,
  AuthenticatedVenueBookingsIndexRoute: AuthenticatedVenueBookingsIndexRoute,
  AuthenticatedVenuesIndexRoute: AuthenticatedVenuesIndexRoute,
  AuthenticatedEventRequestsReopenDraftIdRoute:
    AuthenticatedEventRequestsReopenDraftIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSmokeRoute: ApiSmokeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronNotificationsRoute: ApiCronNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
